[package]
name = "hayaku-simple-path"
version = "0.1.0"
authors = ["nokaa <nokaa@cock.li>"]

[dependencies]
log = "0.3.6"

[dependencies.hayaku-http]
git = "https://github.com/hayaku-rs/hayaku-http.git"
